### ISSUE TITLE
[BUG] Image optimaizer tools throw library error

### ISSUE THREAD

**Issue by RodrigoTomeES** [ObuchiYuki/DevToysMac#7] opened 2022-02-04 08:55 UTC
Hello,

I am very exciting with this version of DevToys for Mac, I already tried and I it is great. But I found that when I tring to compress an PNG and JPG image it throw an error with the library libpng16.16.dylib and jpegoptim. It seems that the libraries are missing from the application. This error occur in all optimizer levels.

<img width="1082" alt="imagen" src="https://user-images.githubusercontent.com/13077343/152500019-6907b9f9-57e1-46ea-9a9f-46192e07af20.png">

**Comment by ObuchiYuki** [comment] 2022-02-04 10:26
Hi!

Thank you for the issue and contribution, I am very happy that you are using DevToys for mac.
I'm very glad you're using DevToys for mac. This bug seems to be caused by the binary being dependent on my environment. I will fix the contents of the binary.

**Comment by ObuchiYuki** [comment] 2022-02-13 10:22
@RodrigoTomeES 
Hello! This bug fixed in version 0.0.7!
Here you can get the new version. 
https://github.com/ObuchiYuki/DevToysMac/releases/tag/0.0.7.2

**Closed by ObuchiYuki** 2022-02-13 10:22 UTC
